server:
  port: 8848

spring:
  application:
    name: my-shiro
  #数据库配置
  datasource:
    url: jdbc:mysql://43.142.15.67:3306/sys_abc?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis配置
  redis:
    database: 0
    host: 43.142.15.67
    port: 6900
    timeout: 30000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 10000

#  Spring Boot 2.1 默认禁用 bean 覆盖作为防御方法,这里选择打开
  main:
    allow-bean-definition-overriding: true

#mybaits配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com/wt/dao/entity

#日志级别和日志输出地方
#logging:
#  level: info
#  file: ./logs




